@ProductWarehouse.API_HostAddress = https://localhost:7092
@ProductId = d81284fb-4492-4521-1671-08dc2b0eadce
@UserId = 96174bfc-383a-464b-ac51-ed81fd55842c
@SizeId = 2a5b8d45-bfcd-4ae7-b351-ac6658d2bbb4
@GroupId = cc458d23-fae6-4b7b-bfc5-399e272442c6

### Get Basket
GET {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}

### Delete Basket
DELETE {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}

### Add Basket Line
POST {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}
Content-Type: application/json

{
  "productId": "d81284fb-4492-4521-1671-08dc2b0eadce",
  "quantity": 1,
  "price": 1110,
  "sizeId": "0234522f-d731-4660-af41-27529d538755"
}

### Delete Basket Line
DELETE {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}/58be69e2-f4c4-4f40-f7d3-08dc2b9e1dce

### Update Basket Line
PUT {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}
Content-Type: application/json

{
  "basketLine": {
  "productId": "{{ProductId}}",
  "quantity": 10
  }
}

### Get Orders
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}

### Get Order
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}/92f8de45-6224-44d0-f190-08dc2b9ff824

### Create Order
POST {{ProductWarehouse.API_HostAddress}}/api/orders
Content-Type: application/json

{
  "userId": "{{UserId}}",
  "totalAmount": 10,
  "orderLines": [
    {
      "productId": "{{ProductId}}",
      "quantity": 1,
      "price": 10,
      "sizeId": "{{SizeId}}"
    }
  ]
}
}

### Partially Update Order
PATCH {{ProductWarehouse.API_HostAddress}}/api/orders/92f8de45-6224-44d0-f190-08dc2b9ff824
Content-Type: application/json-patch+json

[
   {
    "value": "123.45",
    "path": "/TotalAmount",
    "op": "replace"
  }
]

### Delete Order
DELETE {{ProductWarehouse.API_HostAddress}}/api/orders/7a5ea64b-da98-4219-b8a3-08dc2b9fa204

### Get Products
GET {{ProductWarehouse.API_HostAddress}}/api/products

### Get Products by Filter
GET {{ProductWarehouse.API_HostAddress}}/api/products/filter?minPrice=10&maxPrice=100

### Get Product
GET {{ProductWarehouse.API_HostAddress}}/api/products/d81284fb-4492-4521-1671-08dc2b0eadce

### Create Product
POST {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json
 
{
    "title": "Product 221",
    "description": "Description of Product 3",
    "photo": "product3.jpg",
    "price": 39.99,
    "brandId": "eb2abbfc-7076-463f-a861-8bd84c4ddfcf",
    "sizes": [
      {
        "id": "0234522f-d731-4660-af41-27529d538755",
        "quantityInStock": 16
      }
    ],
    "groups": [
      {
        "id": "cc458d23-fae6-4b7b-bfc5-399e272442c6"
      }
    ]
}

### Update Product
PUT {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json

{
    "id": "062e76d9-8ab1-466d-d538-08dc2ba23d4a",
     "title": "ddd",
    "description": "wee",
    "price": 125.00
}

### Delete Product
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/7a154536-56b4-4863-d537-08dc2ba23d4a



GET {{ProductWarehouse.API_HostAddress}}/api/Products
Accept: application/json

###

GET {{ProductWarehouse.API_HostAddress}}/api/Products/filter?MinPrice=10&MaxPrice=89&Highlight=red,blue&Size=M

### Get Product Groups
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups

### Create Product Group
POST {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups
Content-Type: application/json

{
    "groupId": "{{GroupId}}"
}

### Delete Product Group
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups/{{GroupId}}

### Get Product Sizes
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes

### Create Product Size
POST {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes
Content-Type: application/json

{
    "sizeId": "{{SizeId}}",
    "quantityInStock": 10
}

### Delete Product Size
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes/{{SizeId}}

### Update Product Size
PUT {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes/0234522f-d731-4660-af41-27529d538755?QuantityInStock=18
