@ProductWarehouse.API_HostAddress = http://localhost:5068
@BrandId = d6f201af-cf75-40d9-814a-1e0d17e9796c
@ProductId = 11ead65f-14e8-4362-1b2f-08dc2c6aea3f
@UserId = eb1bd4c7-0b80-40a9-a462-2b5a487bddfd
@SizeId = da35ec2b-24e1-4652-ab48-7671b93b5edc
@GroupId = cd95a5b4-efb0-4755-9379-73a81a3a2f9f
@OrderId = 43a7521f-7e8f-431b-cf06-08dc2c6cf3b1

### Get Basket
GET {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}

### Delete Basket
DELETE {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}

### Add Basket Line
POST {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}
Content-Type: application/json

{
  "productId": "{{ProductId}}",
  "quantity": 1,
  "price": 1110,
  "sizeId": "{{SizeId}}"
}

### Delete Basket Line
DELETE {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}/d0a8f206-f901-418f-3f71-08dc2c82d4d9

### Update Basket Line
PUT {{ProductWarehouse.API_HostAddress}}/api/basket/{{UserId}}
Content-Type: application/json

{
  "basketLine": {
    "id": "215132c7-dca0-4028-2bc4-08dc2c83de1f",
    "productId": "{{ProductId}}",
    "quantity": 10,
    "price" : "20",
    "sizeId": "{{SizeId}}"
  }
}

### Get Orders
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}

### Get Order
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}/{{OrderId}}

### Create Order
POST {{ProductWarehouse.API_HostAddress}}/api/orders
Content-Type: application/json

{
  "userId": "{{UserId}}",
  "totalAmount": 10,
    "orderLines": [
    {
      "productId": "11ead65f-14e8-4362-1b2f-08dc2c6aea3f",
      "quantity": 1,
      "price": 1110.00,
      "sizeId": "da35ec2b-24e1-4652-ab48-7671b93b5edc"
    },
    {
      "productId": "11ead65f-14e8-4362-1b2f-08dc2c6aea3f",
      "quantity": 1,
      "price": 1110.00,
      "sizeId": "7aee3527-c299-4c13-b907-ecaa57f9a655"
    }
  ]
}


### Partially Update Order
PATCH {{ProductWarehouse.API_HostAddress}}/api/orders/f93a44ec-26a7-4857-8ec6-08dc2c84457f
Content-Type: application/json-patch+json

[
   {
    "value": "6ee5e273-82f0-40a0-aa0e-2f221a2588b0",
    "path": "/statusId",
    "op": "replace"
  }
]

### Delete Order
DELETE {{ProductWarehouse.API_HostAddress}}/api/orders/43a7521f-7e8f-431b-cf06-08dc2c6cf3b1

### Get Products
GET {{ProductWarehouse.API_HostAddress}}/api/products

### Get Products by Filter
GET {{ProductWarehouse.API_HostAddress}}/api/products/filter?minPrice=10&maxPrice=100

### Get Product
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}

### Create Product
POST {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json
 
{
    "title": "Product X",
    "description": "Description of Product 3",
    "photo": "product3.jpg",
    "price": 39.99,
    "brandId": "{{BrandId}}",
    "sizes": [
      {
        "id": "{{SizeId}}",
        "quantityInStock": 16
      }
    ],
    "groups": [
      {
        "id": "{{GroupId}}"
      }
    ]
}

### Update Product
PUT {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json

{
    "id": "11ead65f-14e8-4362-1b2f-08dc2c6aea3f",
    "title": "NEW",
    "description": "NEW",
    "price": 10000
}

### Delete Product
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/11ead65f-14e8-4362-1b2f-08dc2c6aea3f


GET {{ProductWarehouse.API_HostAddress}}/api/Products
Accept: application/json

###

GET {{ProductWarehouse.API_HostAddress}}/api/Products/filter?MinPrice=10&MaxPrice=89&Highlight=red,blue&Size=M

### Get Product Groups
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups

### Create Product Group
POST {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups
Content-Type: application/json

{
    "groupId": "0e596ec6-bc97-4e5d-9593-69387ac3cb03"
}

### Delete Product Group
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups/{{GroupId}}

### Get Product Sizes
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes

### Create Product Size
POST {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes
Content-Type: application/json

{
    "id": "{{ProductId}}",
    "sizeId": "ea88c493-9e58-47c7-80cd-766ac89a7a01",
    "quantityInStock": 10
}
### Update Product Size
PUT {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes/ea88c493-9e58-47c7-80cd-766ac89a7a01?QuantityInStock=18


### Delete Product Size
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes/{{SizeId}}