@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId = 11ead65f-14e8-4362-1b2f-08dc2c6aea3f
@UserId = eb1bd4c7-0b80-40a9-a462-2b5a487bddfd
@SizeId = 2aef86e1-2190-455a-890f-c19b276c97e1

### Get Basket
GET {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}

### Delete Basket
DELETE {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}

### Add Basket Line
POST {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}
Content-Type: application/json

{
  "productId": "{{ProductId}}",
  "quantity": 1,
  "price": 1110,
  "sizeId": "{{SizeId}}"
}

### Delete Basket Line
DELETE {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}/d3940cf3-a9e6-4764-8c88-08dc31e74d8d

### Update Basket Line
PUT {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}
Content-Type: application/json

{
  "id": "3dbc5af7-f015-437d-9731-dead1be11a1d",
  "productId": "{{ProductId}}",
  "quantity": 10,
  "price" : 0,
  "sizeId": "{{SizeId}}"
}