@ProductWarehouse.API_HostAddress = http://localhost:5068
@BrandId = 656b14b5-849b-4f18-b149-3391429960cb
@ProductId = 288d5d4f-a2fd-4e01-4a21-08dc2c862878
@UserId = eb1bd4c7-0b80-40a9-a462-2b5a487bddfd
@SizeId = 9082a2cc-3235-4aed-89ac-c63d67203894
@GroupId = 597b7de6-62a3-4fe2-969b-2ecd18b42892
@OrderId = 43a7521f-7e8f-431b-cf06-08dc2c6cf3b1

### Get Products
GET {{ProductWarehouse.API_HostAddress}}/api/products

### Get Products by Filter
GET {{ProductWarehouse.API_HostAddress}}/api/products/filter?minPrice=10&maxPrice=100

### Get Product
GET {{ProductWarehouse.API_HostAddress}}/api/products/a56b78bc-55f8-4fc4-139d-08dc338a8040

### Create Product
POST {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json
 
{
    "title": "Product X",
    "description": "Description of Product 3",
    "photo": "product3.jpg",
    "price": 10,
    "brandId": "{{BrandId}}",
    "sizes": [
      {
        "id": "{{SizeId}}",
        "quantityInStock": 10
      }
    ],
    "groups": [
      {
        "id": "{{GroupId}}"
      }
    ]
}

### Update Product
PUT {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json

{
  "id": "d927799f-5e68-4783-ba35-08dc33bc4507",
  "title": "Product",
  "description": "Product Descr",
  "brandId": "e8c25c64-44a8-4481-84fb-29718c37c6b4",
  "price": 100,
  "sizes": [
    {
      "id": "9082a2cc-3235-4aed-89ac-c63d67203894",
      "quantityInStock": 10
    }
  ],
  "groups": [
    {
      "id": "cd95a5b4-efb0-4755-9379-73a81a3a2f9f"
    }
  ]
}

### Delete Product
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/a56b78bc-55f8-4fc4-139d-08dc338a8040
