@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId = 1ea10c67-d092-4348-9b3e-65587ab98d5b
@GroupId = c6d8c25e-2810-439c-960d-a34191d8f46c

### Get Product Groups
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups

### Create Product Group
POST {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups
Content-Type: application/json

{
    "id":"{{ProductId}}",
    "groupId": "{{GroupId}}"
}

### Delete Product Group
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups/{{GroupId}}
