@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId = 11ead65f-14e8-4362-1b2f-08dc2c6aea3f
@GroupId = cd95a5b4-efb0-4755-9379-73a81a3a2f9f

### Get Product Groups
GET {{ProductWarehouse.API_HostAddress}}/api/products/11ead65f-14e8-4362-1b2f-08dc2c6aea3f/groups

### Create Product Group
POST {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups
Content-Type: application/json

{
    "groupId": "cd95a5b4-efb0-4755-9379-73a81a3a2f9f"
}

### Delete Product Group
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/groups/{{GroupId}}
