@ProductWarehouse.API_HostAddress = http://localhost:5068
@BrandId = d6f201af-cf75-40d9-814a-1e0d17e9796c
@ProductId = 288d5d4f-a2fd-4e01-4a21-08dc2c862878
@UserId = eb1bd4c7-0b80-40a9-a462-2b5a487bddfd
@SizeId = ea88c493-9e58-47c7-80cd-766ac89a7a01
@GroupId = 0e596ec6-bc97-4e5d-9593-69387ac3cb03
@OrderId = 43a7521f-7e8f-431b-cf06-08dc2c6cf3b1

### Get Products
GET {{ProductWarehouse.API_HostAddress}}/api/products

### Get Products by Filter
GET {{ProductWarehouse.API_HostAddress}}/api/products/filter?minPrice=10&maxPrice=100

### Get Product
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}

### Create Product
POST {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json
 
{
    "title": "Product X",
    "description": "Description of Product 3",
    "photo": "product3.jpg",
    "price": 10,
    "brandId": "{{BrandId}}",
    "sizes": [
      {
        "id": "{{SizeId}}",
        "quantityInStock": 10
      }
    ],
    "groups": [
      {
        "id": "{{GroupId}}"
      }
    ]
}

### Update Product
PUT {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json

{
  "id": "{{ProductId}}",
  "title": "Product X",
  "description": "Description of Product 3",
  "brandId": "e8c25c64-44a8-4481-84fb-29718c37c6b4",
  "price": 10,
  "sizes": [
    {
      "id": "ea88c493-9e58-47c7-80cd-766ac89a7a01",
      "quantityInStock": 100000
    }
  ],
  "groups": [
    {
      "id": "cd95a5b4-efb0-4755-9379-73a81a3a2f9f"
    }
  ]
}

### Delete Product
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/bf980d52-5df0-44ac-faa5-08dc2c6c47b9
