@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId = 288d5d4f-a2fd-4e01-4a21-08dc2c862878
@UserId = eb1bd4c7-0b80-40a9-a462-2b5a487bddfd
@SizeId = 2aef86e1-2190-455a-890f-c19b276c97e1

### Get Basket
GET {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}

### Delete Basket
DELETE {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}

### Add Basket Line
POST {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}
Content-Type: application/json

{
  "productId": "{{ProductId}}",
  "quantity": 1,
  "sizeId": "da35ec2b-24e1-4652-ab48-7671b93b5edc"
}

### Delete Basket Line
DELETE {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}/6fffd403-410c-4152-c98f-08dc33a18408

### Update Basket Line
PUT {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}
Content-Type: application/json

{
  "id": "eed01306-109a-4938-c990-08dc33a18408",
  "productId": "{{ProductId}}",
  "quantity": 2,
  "sizeId": "da35ec2b-24e1-4652-ab48-7671b93b5edc"
}