@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId = 11ead65f-14e8-4362-1b2f-08dc2c6aea3f
@UserId = eb1bd4c7-0b80-40a9-a462-2b5a487bddfd
@SizeId = 2aef86e1-2190-455a-890f-c19b276c97e1

### Get Basket
GET {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}

### Delete Basket
DELETE {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}

### Add Basket Line
POST {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}
Content-Type: application/json

{
  "productId": "{{ProductId}}",
  "quantity": 1,
  "price": 1110,
  "sizeId": "{{SizeId}}"
}

### Delete Basket Line
DELETE {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}/47ad195b-95cb-4690-e7f5-08dc32dbf94a

### Update Basket Line
PUT {{ProductWarehouse.API_HostAddress}}/api/baskets/{{UserId}}
Content-Type: application/json

{
  "id": "47ad195b-95cb-4690-e7f5-08dc32dbf94a",
  "productId": "a71b20c6-894e-40ad-29d5-08dc3209ece8",
  "quantity": 2,
  "price" : 20,
  "sizeId": "da35ec2b-24e1-4652-ab48-7671b93b5edc"
}