@ProductWarehouse.API_HostAddress = http://localhost:5068
@BrandId =62262d18-7d45-4347-8994-d276fff745fa
@ProductId =89cca55f-7393-4ebd-ae66-f0d3ef613c3d
@UserId = b491e486-c1b1-44b8-9e83-6e226073d7f2
@SizeId = 6bec10ff-0fbd-4881-99f4-6acf188d2bea
@GroupId = c6d8c25e-2810-439c-960d-a34191d8f46c
@OrderId = 43a7521f-7e8f-431b-cf06-08dc2c6cf3b1

### Get Products
GET {{ProductWarehouse.API_HostAddress}}/api/products

### Get Products by Filter
GET {{ProductWarehouse.API_HostAddress}}/api/products/filter?minPrice=10&maxPrice=100

### Get Product
GET {{ProductWarehouse.API_HostAddress}}/api/products/d21fc7f7-daff-455c-a1b8-4c709a26ba6e

### Create Product
POST {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json
 
{
    "title": "check if rolback works",
    "description": "D",
    "photo": "p.jpg",
    "price": 1,
    "brandId": "{{BrandId}}",
    "sizes": [
    { "id":"{{SizeId}}",
     "QuantityInStock":2
    }
    ],
    "groups": [
      {
        "id": "{{GroupId}}"
      }
    ]
}

### Update Product
PUT {{ProductWarehouse.API_HostAddress}}/api/products
Content-Type: application/json

{
  "id": "d21fc7f7-daff-455c-a1b8-4c709a26ba6e",
  "title": "Product",
  "description": "Product Descr",
  "brandId": "{{BrandId}}",
  "price": 100,
  "sizes": [
   
  ],
  "groups": [
   
  ]
}

### Delete Product
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/00858d45-fcc2-4d44-b809-2087d566e679
