@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId =7f08bcd5-44c9-4198-908f-574c450e0cc7
@SizeId = de75ba98-3197-485b-b9a8-40593d6bd5e3

### Get Product Sizes
GET {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes

### Create Product Size
POST {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes
Content-Type: application/json

{
    "id": "{{ProductId}}",
    "sizeId": "{{SizeId}}",
    "quantityInStock": 10
}

### Update Product Size
PUT {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes/{{SizeId}}?QuantityInStock=1


### Delete Product Size
DELETE {{ProductWarehouse.API_HostAddress}}/api/products/{{ProductId}}/sizes/{{SizeId}}