@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId =1ea10c67-d092-4348-9b3e-65587ab98d5b
@UserId = b491e486-c1b1-44b8-9e83-6e226073d7f2
@SizeId = 6bec10ff-0fbd-4881-99f4-6acf188d2bea
@OrderId = 43a7521f-7e8f-431b-cf06-08dc2c6cf3b1

### Get Orders
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}

### Get Order
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}/585ee648-e31f-4a2a-b37c-a5e5a15c4a0d

### Create Order
POST {{ProductWarehouse.API_HostAddress}}/api/orders
Content-Type: application/json

{
  "userId": "{{UserId}}",
  "totalAmount": 10,
    "orderLines": [
    {
      "productId": "{{ProductId}}",
      "quantity": 1,
      "price": 1110.00,
      "sizeId": "{{SizeId}}"
    }
  ]
}

### Partially Update Order
PATCH {{ProductWarehouse.API_HostAddress}}/api/orders/2be26ede-cee2-43c9-3997-08dc338dbf74
Content-Type: application/json-patch+json

[
   {
    "value": "6ee5e273-82f0-40a0-aa0e-2f221a2588b0",
    "path": "/statusId",
    "op": "replace"
  }
]

### Delete Order
DELETE {{ProductWarehouse.API_HostAddress}}/api/orders/ca087a94-4452-48b7-4db6-08dc3381e749