@ProductWarehouse.API_HostAddress = http://localhost:5068
@ProductId = b5415b0d-9264-4c93-a64c-1439a7ffdbc8
@UserId = 1fd3d9f7-c171-4596-b332-fa0f65d0f057
@OrderId = 43a7521f-7e8f-431b-cf06-08dc2c6cf3b1
@SizeId = 6bec10ff-0fbd-4881-99f4-6acf188d2bea

### Get Orders
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}

### Get Order
GET {{ProductWarehouse.API_HostAddress}}/api/orders/{{UserId}}/41e5cf2a-aa17-4b81-9389-836cdd84c889

### Create Order
POST {{ProductWarehouse.API_HostAddress}}/api/orders
Content-Type: application/json

{
  "userId": "{{UserId}}",
  "totalAmount": 10,
    "orderLines": [
    {
      "productId": "{{ProductId}}",
      "quantity": 1,
      "price": 1110.00,
      "sizeId": "{{SizeId}}"
    }
  ]
}


### Partially Update Order
PATCH {{ProductWarehouse.API_HostAddress}}/api/orders/2be26ede-cee2-43c9-3997-08dc338dbf74
Content-Type: application/json-patch+json

[
   {
    "value": "6ee5e273-82f0-40a0-aa0e-2f221a2588b0",
    "path": "/statusId",
    "op": "replace"
  }
]

### Delete Order
DELETE {{ProductWarehouse.API_HostAddress}}/api/orders/ca087a94-4452-48b7-4db6-08dc3381e749
